[package]
name = "flowrs"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
itertools = "0.14.0"
tempfile = "3.20.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tch = "0.5"
lazy_static = "1.4"

